from fastapi.testclient import TestClient
from backend.app.main import app  # adjust import if your app is defined elsewhere

client = TestClient(app)


def test_create_review():
    payload = {
        "movie_id": 1,
        "rating": 4,
        "title": "Test Review",
        "body": "This review is generated by an automated test."
    }
    response = client.post("/reviews", json=payload)
    assert response.status_code in (200, 201)


def test_create_review_invalid_rating():
    payload = {
        "movie_id": 1,
        "rating": 6,
        "title": "Invalid Review",
        "body": "This should be rejected."
    }
    response = client.post("/reviews", json=payload)
    assert response.status_code in (400, 422)


def test_create_review_missing_fields():
    # missing rating and title
    payload = {
        "movie_id": 1,
        "body": "Missing required fields"
    }
    response = client.post("/reviews", json=payload)
    assert response.status_code in (400, 422)


def test_get_review():
    # create then retrieve
    payload = {
        "movie_id": 10,
        "rating": 5,
        "title": "Get Test",
        "body": "Get review body"
    }
    create_resp = client.post("/reviews", json=payload)
    assert create_resp.status_code in (200, 201)
    data = create_resp.json() if create_resp.content else {}
    review_id = data.get("id")
    assert review_id is not None

    get_resp = client.get(f"/reviews/{review_id}")
    assert get_resp.status_code == 200
    got = get_resp.json()
    assert got.get("id") == review_id
    assert got.get("movie_id") == payload["movie_id"]


def test_list_reviews():
    # ensure endpoint returns a list and can include created reviews
    payload = {
        "movie_id": 20,
        "rating": 3,
        "title": "List Test",
        "body": "List review body"
    }
    client.post("/reviews", json=payload)
    resp = client.get("/reviews")
    assert resp.status_code == 200
    assert isinstance(resp.json(), list)


def test_update_review():
    # create, update, then verify
    payload = {
        "movie_id": 30,
        "rating": 2,
        "title": "Update Test",
        "body": "Original"
    }
    create_resp = client.post("/reviews", json=payload)
    assert create_resp.status_code in (200, 201)
    data = create_resp.json() if create_resp.content else {}
    review_id = data.get("id")
    assert review_id is not None

    update_payload = {"rating": 4, "title": "Updated Title"}
    update_resp = client.put(f"/reviews/{review_id}", json=update_payload)
    assert update_resp.status_code in (200, 204)

    # fetch to confirm update (if 204 returned, GET will check)
    get_resp = client.get(f"/reviews/{review_id}")
    assert get_resp.status_code == 200
    got = get_resp.json()
    assert got.get("rating") == update_payload["rating"]
    assert got.get("title") == update_payload["title"]


def test_delete_review():
    create_payload = {
        "movie_id": 2,
        "rating": 3,
        "title": "Review To Delete",
        "body": "Temp review for deletion test"
    }
    create_resp = client.post("/reviews", json=create_payload)
    assert create_resp.status_code in (200, 201)
    data = create_resp.json() if create_resp.content else {}
    review_id = data.get("id")
    assert review_id is not None

    delete_resp = client.delete(f"/reviews/{review_id}")
    assert delete_resp.status_code in (200, 204)

    # ensure it's gone
    get_after = client.get(f"/reviews/{review_id}")
    assert get_after.status_code in (404,)


def test_delete_nonexistent_review():
    # attempt to delete an id unlikely to exist
    delete_resp = client.delete("/reviews/999999999")
    assert delete_resp.status_code in (400, 404, 422)